name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18 with cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Backend/package-lock.json

          
      - name: Install dependencies
        working-directory: Backend
        run: npm ci

      - name: Run tests
        working-directory: Backend
        run: npm test
